### ISSUE TITLE
MLReef review

### ISSUE THREAD

**Issue by Aparichit0000** [MLReef/mlreef#5]
The whole idea of collaborating machine learning algorithm and reusing them is cool. As a first time user, I did not understand the basics though, so I found it really difficult to experiment and learn.

**Comment by cpmlreef** [comment]
Hi @Aparichit0000, if you want we can have a short walkthrough where you point out the things that you did not understand. This helps us tremendously improve user flow and core mechanics. 
would you be open for this?
