### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by christianokoye** [MLReef/mlreef#6]
I am writing a review after trying my hands on new MLReef project. 

The project went smoothly as I created and executed different data sets and paths. 

I was work on the data in the project for detecting masks on people's face and it shows promising outputs.

I am looking forward work more and improve my skills on this.

Thank you

**Comment by Debjanibo** [comment]
Thank you

**Comment by cpmlreef** [comment]
Thank you @Debjanibo - if you need anything or we can support you, just let us know! :)

**Comment by christianokoye** [comment]
Thanks for resolving! Best wishes
